PR141 - Zach's PR Code Review
hackgvl/hackgreenville-com pull request #154
Opened 2023-07-24 16:35 UTC by bogdankharchenko

2023-07-24 16:38 UTC, bogdankharchenko commented on app/Console/Commands/PullOrgsCommand.php
> +        $this->inactive_category = Category::firstOrCreate(['label' => 'In Active']);
```suggestion
        $this->inactive_category = Category::firstOrCreate(['label' => 'Inactive']);
```

2023-07-24 17:58 UTC, allella commented on app/Console/Commands/PullOrgsCommand.php
> +        $this->inactive_category = Category::firstOrCreate(['label' => 'In Active']);
Concur on "Inactive" over "In Active"

2023-07-24 21:13 UTC, zach2825 commented
I think this should work in a command as well 

Closes https://github.com/hackgvl/hackgreenville-com/issues/113
Closes https://github.com/hackgvl/hackgreenville-com/issues/109

2023-07-25 13:31 UTC, zach2825 requested changes
Minor changes that I've found. But, these are some amazing updates.

2023-07-25 13:31 UTC, zach2825 commented on app/Data/OrganizationData.php
> +    public function resolveCategory(): Model|Category
Mind changing this return type to `Category`?

2023-07-25 13:31 UTC, zach2825 commented
I tried to make the changes and push them up, but I don't have permission or something random like that. The things I found are very minor.

2023-07-25 13:35 UTC, bogdankharchenko commented on app/Console/Commands/PullEventsCommand.php
> +    public function handleRow(EventDataTransformer $data)
I personally turn that inspection off in my IDE simply because I want the he variable to make sense

2023-07-25 13:41 UTC, allella commented
Thanks @bogdankharchenko.

My main questions is with the app/Console/Kernel.php having a scheduled import.  Is this hooking the imports on to a user's visit?  If so, I assume that would get queued on the end and not impact their browsing experience.

Still, we've had a cron job, which might actually be too frequent, but I wonder if we should continue using a cron job to trigger.

If so, what would be the best cron command to schedule.

The current on is below, and again, it looks like it runs every minute, which is more than necessary.

`* * * * * cd ~/public_html/hack && php artisan schedule:run >> /dev/null 2>&1`

CC'ing @zach2825

2023-07-25 13:49 UTC, bogdankharchenko commented
@allella once this is merged, you should close this PR: https://github.com/hackgvl/hackgreenville-com/pull/141

As this PR superseeds it, just want to make sure you do not merge both.

2023-07-25 13:53 UTC, irby commented on tests/Feature/CancelEventCommandTest.php
> +it('marks event as canceled if not in the API response', function () {
This is really cool syntactically, looks like a Javascript test. 
Yay for tests!

2023-07-25 13:55 UTC, bogdankharchenko commented on tests/Feature/CancelEventCommandTest.php
> +it('marks event as canceled if not in the API response', function () {
I'm personally not a fan of this syntax for php simply because its out of context comparing to the rest of the code base, but Zach wants to use this - all good.

2023-07-25 14:16 UTC, irby commented on tests/Feature/CancelEventCommandTest.php
> +it('marks event as canceled if not in the API response', function () {
Are these tests visible using the `php artisan test` command, or is there a different command to run these tests?

2023-07-25 15:36 UTC, bogdankharchenko commented on tests/Feature/CancelEventCommandTest.php
> +it('marks event as canceled if not in the API response', function () {
Same command

2023-07-25 16:11 UTC, zach2825 commented on app/Console/Commands/PullEventsCommand.php
> +    public function handleRow(EventDataTransformer $data)
We should probably adhere to standards as much as possible, but im not going to hold up a merge for this. We'll have to fix it later.

2023-07-25 16:13 UTC, zach2825 commented on tests/Feature/CancelEventCommandTest.php
> +it('marks event as canceled if not in the API response', function () {
You can also run `yarn test` which basically runs `php artisan test --parallel` i do that because i have a terminal alias yt that runs `yarn test`

2023-07-25 16:15 UTC, zach2825 approved these changes
Looks good :100: :fireworks:

2023-07-25 16:53 UTC, irby reviewed
Have some comments.

Due to the size of this PR, it might be due for a separate PR to add unit tests behind the classes I've commented out. Have a comment about removing dead code from a file.

2023-07-25 16:53 UTC, irby commented on app/Console/Commands/PullEventsCommand.php
> +            ->map(fn ($event_from_api) => EventDataTransformer::from($event_from_api));
This looks great. Much cleaner. 👍🏻

2023-07-25 16:53 UTC, irby commented on app/Providers/EventServiceProvider.php
> +            //            'App\Events\Event' => [
Should we remove these commented out items?

2023-07-25 16:53 UTC, irby commented on app/Data/OrganizationData.php
> +    public function isOrganizationInactive(): bool
Might be good practice to write unit tests against these methods.

2023-07-25 16:53 UTC, irby commented on app/Data/EventDataTransformer.php
> +    public function getCancelledAtOrNull(): ?Carbon
Might be good practice to write unit tests against these methods.

2023-07-25 16:53 UTC, irby commented on app/Http/Clients/UpstateClient.php
> +        return Http::baseUrl(config('app.events_api_domain'))
Might be good practice to write unit tests against these methods.

2023-07-25 16:55 UTC, bogdankharchenko commented on app/Http/Clients/UpstateClient.php
> +        return Http::baseUrl(config('app.events_api_domain'))
This is a framework level function - we shouldn't test the framework =)

2023-07-25 16:56 UTC, bogdankharchenko commented on app/Data/EventDataTransformer.php
> +    public function getCancelledAtOrNull(): ?Carbon
Our feature test covers this already.

2023-07-25 16:56 UTC, bogdankharchenko commented on app/Providers/EventServiceProvider.php
> +            //            'App\Events\Event' => [
agreed

2023-07-25 17:03 UTC, irby commented on app/Data/EventDataTransformer.php
> +    public function getCancelledAtOrNull(): ?Carbon
I see it covers the condition of `status === cancelled`. What about a test when it's not cancelled?

2023-07-25 17:14 UTC, irby approved these changes

2023-07-26 16:35 UTC, allella commented
Looks like we have three thumbs up. Are we ready to merge this @bogdankharchenko ?

2023-07-26 19:17 UTC, bogdankharchenko commented
@allella yeah for sure

2023-07-26 19:22 UTC, merged