Implement Meetup GraphQL compatibility
hackgvl/hackgreenville-com pull request #345
Opened 2024-07-22 04:13 UTC by irby

Add in GraphQL support for the Meetup API

2024-07-25 01:04 UTC, bogdankharchenko requested changes
@irby great work on the import!  A few small house keeping things around where the code lives, but overall it works on my machine =)

2024-07-25 01:04 UTC, bogdankharchenko commented on app-modules/event-importer/src/Providers/Keys/.gitignore
> +*.pem
Let's bring this up to the parent .gitignore and delete this "Keys" directory all together.  Since we wont commit any keys, I don't think we need this folder.

2024-07-25 01:04 UTC, bogdankharchenko commented on config/event-import-handlers.php
> +    'meetup_graphql_private_key_path' => env('EVENT_IMPORTER_MEETUP_GRAPHQL_PRIVATE_KEY_PATH', __DIR__ . '/../app-modules/event-importer/src/Providers/Keys/meetup-graphql.pem'),
```suggestion
    'meetup_graphql_private_key_path' => env('EVENT_IMPORTER_MEETUP_GRAPHQL_PRIVATE_KEY_PATH'),
```

We should just leave this blank -- if the pem file missing, let's throw an exception in the handler.

2024-07-25 01:04 UTC, bogdankharchenko commented on app-modules/event-importer/src/Providers/MeetupGraphqlTokenProvider.php
> +        $privateKey = file_get_contents(config('event-import-handlers.meetup_graphql_private_key_path'));
Before we perform file_get_contents -- we should, 
1. Check if the env is actually set -- if it is not set, throw a runtime exception
2. Ensure file exists.

2024-07-25 13:12 UTC, allella commented on app-modules/event-importer/src/Providers/Keys/.gitignore
> +*.pem
Just curious since this is a file, and we probably aren't sharing it with all future devs, will running the import break if someone doesn't have a .pem file. Or, are we able to gracefully fail in that case?

2024-07-26 12:42 UTC, irby commented on app-modules/event-importer/src/Providers/MeetupGraphqlTokenProvider.php
> +        $privateKey = file_get_contents(config('event-import-handlers.meetup_graphql_private_key_path'));
Sure, makes sense. Will push a change out later to fix this.

2024-07-26 12:43 UTC, irby commented on app-modules/event-importer/src/Providers/Keys/.gitignore
> +*.pem
It will break if the runner doesn't have a pem file and at least one org has `meetup_graphql` set. It will not fail gracefully, and not sure if we'd want it to (what happens if the server tries to run this import and it doesn't have the key?)

2024-07-26 12:44 UTC, irby commented on app-modules/event-importer/tests/Feature/MeetupRestTest.php
> -        $this->assertNull($active_event->cancelled_at);
Nah, I just felt that since we're checking on the cancelled_at property being set in one test, it makes sense to assert that cancelled_at is not set under certain conditions.

2024-07-26 12:44 UTC, irby commented on app-modules/event-importer/src/Services/MeetupGraphqlHandler.php
> +        $end_date = now()->addDays($this->max_days_in_future)->startOfDay();
Made change.

2024-07-26 13:11 UTC, allella commented on app-modules/event-importer/src/Providers/Keys/.gitignore
> +*.pem
The concern is more for devs. 

They obviously won't have the production .pem and I'm wondering if we foresee devs wanting to run the event import and if the Meetup GraphQL import without a .pem is going to make that entire process fail, or if it would be fairly easy to avoid or workaround.

2024-07-26 14:19 UTC, irby commented on app-modules/event-importer/src/Providers/Keys/.gitignore
> +*.pem
That's fair. I think we could use an environment variable like APP_ENV where devs would run it with `dev` and print out a warning for devs but throw an exception for prod. I'll defer to @bogdankharchenko on the approach we should take

2024-07-29 15:42 UTC, irby commented
@bogdankharchenko I have addressed all feedback -- one outstanding question from @allella regarding how to handle local development with respect to the required private key file.

https://github.com/hackgvl/hackgreenville-com/pull/345#discussion_r1693041347

2024-07-30 13:16 UTC, bogdankharchenko commented
Overall this looks good - one more small comment about tests, but we can live with the exceptions being thrown for missing api keys, missing pem files -- we currently throw exeptions for everbrite as well. 

We may need to introduce a generic exception later which we can catch more efficiently

2024-07-30 14:01 UTC, irby commented on app-modules/event-importer/tests/Feature/MeetupGraphqlTest.php
> +    private function setupTest(): void
Changed!

2024-07-30 14:09 UTC, bogdankharchenko approved these changes

2024-07-31 02:05 UTC, allella approved these changes

2024-07-31 02:06 UTC, merged